In [ ]:
# groups_folder_path = '/content/drive/My Drive/beans'
# categories = ["broken", "insect", "normal"] # 해당 이미지들이 들어가 있는 폴더명 넣어주기 
# num_classes = len(categories)

In [2]:
#pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1320 sha256=039a5a6d34665b365cd6d63473fee7a168aa3d9d3535ec647a162543acf0dc02
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\46\ef\c3\157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


In [1]:
import torch
from torch.autograd import Variable 
import torch.nn as nn 
import torch.nn.functional as F 
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

import os 
from PIL import Image 
import numpy as np
import pandas as pd
from sklearn import datasets, model_selection

In [6]:
import pymongo
import gridfs 
from pymongo import MongoClient

In [3]:
groups_folder_path = './normal_data'
categories = ["normal_align_test_image", "normal_processed_data", "normal_raw_data" ] # 해당 이미지들이 들어가 있는 폴더명 넣어주기 

In [ ]:
# # mongodb에서 사진 불러오기 
# # category 나눠서 들어갈 수 있도록 하기 



# if __name__ == '__main__' :
    
#     # connect to database 
#     client = MongoClient('127.0.0.1', 27017)

    


#     # read in the image 

#     for i,d in enumerate(categories):
#         files = os.listdir(groups_folder_path + '/'+ d)
#         database = client[d]

#         # create a new gridfs object
#         fs = gridfs.GridFS(database)

#         for f in files : 
#             img = open(groups_folder_path + '/'+ d +'/' + f, 'rb')
#             thedata = img.read()
#             # store the data in the database. 
#             # Returns the id of the file in gridFS 
#             stored = fs.put(thedata, filename = f)

    
    
    



#     # retrieve what was just stored 
#     #outputdata = fs.get(stored).read()

#     # create an output file and store the image in the output file 
#     # outfilename = './OpenCV/data/20200508_test1_sample1.jpg'
#     # output = open(outfilename, 'wb')
#     # output.write(outputdata)
#     # # close the output file 
#     # output.close()

#     # for experimental code restore to known state and close connection 

#     #fs.delete(stored)
#     #client.drop_database('example')
#     client.close()

In [50]:
# pip install StringIO

Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement StringIO (from versions: none)
ERROR: No matching distribution found for StringIO


In [52]:
# import base64


In [62]:
# img = Image.open("./normal_data/normal_align_test_image/20200518_test_inadvance1_off.jpeg")
# img.size

(2160, 2160)

In [87]:
import io

In [121]:
data = []
label = []

# groups_folder_path = './normal_data'
# categories = ["normal_align_test_image", "normal_processed_data", "normal_raw_data" ] # 해당 이미지들이 들어가 있는 폴더명 넣어주기 

if __name__ == '__main__' :  
  client = MongoClient('127.0.0.1', 27017)
  # read in the image 
  for i,d in enumerate(categories):
    database  = client[d]
    files     = os.listdir(groups_folder_path + '/'+ d)
    
    # create a new gridfs object
    fs        = gridfs.GridFS(database)

    #print( '->' +  d )
    for f in files : 
      #print( groups_folder_path + '/'+ d +'/' + f )
      fp         = open(groups_folder_path + '/'+ d +'/' + f, 'rb')
      # bytes로 읽는다
      thedata     = fp.read()            
      
      image = Image.open(io.BytesIO(thedata))
      #image.show()
      
      
      
      #print( type(thedata), len(thedata) )
      # 디비에 저장
      stored      = fs.put(thedata, filename = f)      
      # 디비에서 다시 읽는다
      outputdata  = fs.get(stored).read()
      #print( type(outputdata), len(outputdata) )
      #print( '-'*10 )
      
      thedata2 = Image.open(fp, mode='r')
      

      #thedata2 = Image.frombytes('RGB', (2160,2160), outputdata, 'raw')      
      # #thedata = Image.open(StringIO.StringIO(outputdata))
      # # 이미지 흑백으로 변경 
      img = thedata2.convert('L')
      # # 이미지를 28, 28로 일괄 리사이즈 
      resize_img = img.resize((28,28))
      black_resize_img = np.asarray(resize_img)
      # # 가공한 이미지 추가 
      data.append(black_resize_img)
      # # label : broken, insect, normal
      label.append(i)

      fp.close()
      #break


  client.close()

pd.DataFrame(data[0][0]).shape

(28, 1)

In [122]:
data = np.array(data, dtype = 'float32')
label = np.array(label, dtype = 'int64')

train_X, test_X, train_Y, test_Y = model_selection.train_test_split(data, label, test_size = 0.1)

train_X = torch.from_numpy(train_X).float()
train_Y = torch.from_numpy(train_Y).long()

test_X = torch.from_numpy(test_X).float()
test_Y = torch.from_numpy(test_Y).long()

#train = TensorDataset(train_X, train_Y)
#train_loader = DataLoader(train, batch_size = 32, shuffle = True)

In [123]:
train_X

tensor([[[212., 212., 212.,  ..., 213., 213., 213.],
         [212., 212., 212.,  ..., 213., 213., 213.],
         [212., 212., 212.,  ..., 213., 213., 213.],
         ...,
         [214., 214., 214.,  ..., 214., 214., 214.],
         [214., 214., 214.,  ..., 214., 214., 214.],
         [214., 214., 214.,  ..., 214., 214., 214.]],

        [[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         ...,
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.]],

        [[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         ...,
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.]],

In [124]:
train_Y

tensor([2, 1, 1,  ..., 1, 1, 2])

In [125]:
test_X

tensor([[[211., 211., 211.,  ..., 213., 212., 211.],
         [211., 211., 211.,  ..., 213., 212., 211.],
         [211., 211., 211.,  ..., 213., 212., 211.],
         ...,
         [210., 210., 210.,  ..., 211., 212., 211.],
         [210., 210., 210.,  ..., 211., 212., 211.],
         [210., 210., 210.,  ..., 211., 212., 211.]],

        [[209., 209., 209.,  ..., 209., 209., 209.],
         [211., 210., 209.,  ..., 209., 209., 209.],
         [204., 207., 210.,  ..., 209., 209., 209.],
         ...,
         [210., 210., 210.,  ..., 207., 206., 206.],
         [210., 210., 210.,  ..., 207., 206., 206.],
         [210., 210., 210.,  ..., 207., 206., 206.]],

        [[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         ...,
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.]],

In [126]:
test_Y

tensor([2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 0, 1, 2, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1,
        1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1,
        2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2,
        2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2,
        1, 2, 2, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2,
        2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1,
        2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1,
        1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2,
        1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1,
        1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2,
        1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1,
        1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1,

In [127]:
train_X.shape

torch.Size([3056, 28, 28])

In [128]:
train_Y.shape

torch.Size([3056])

In [129]:
test_X.shape

torch.Size([340, 28, 28])

In [130]:
test_Y.shape

torch.Size([340])

In [131]:
# 데이터 차원 맞추기
train_X = train_X.unsqueeze(1)
test_X = test_X.unsqueeze(1)

In [132]:
train_X.shape

torch.Size([3056, 1, 28, 28])

In [133]:
test_X.shape

torch.Size([340, 1, 28, 28])

In [134]:
# 만약 GPU를 사용 가능하다면 device 값이 cuda가 되고, 아니라면 cpu가 됩니다.
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# 랜덤 시드 고정
torch.manual_seed(777)

# GPU 사용 가능일 경우 랜덤 시드 고정
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [135]:
dataset = TensorDataset(train_X, train_Y)
type(dataset)

torch.utils.data.dataset.TensorDataset

In [136]:
learning_rate = 0.001
training_epochs = 15
batch_size = 100

data_loader = torch.utils.data.DataLoader(dataset=dataset,
                                          batch_size=batch_size,
                                          shuffle=True,
                                          drop_last=True)

In [137]:
class CNN(torch.nn.Module):

    def __init__(self):
        super(CNN, self).__init__()
        # 첫번째층
        # ImgIn shape=(?, 28, 28, 1)
        #    Conv     -> (?, 28, 28, 32)
        #    Pool     -> (?, 14, 14, 32)
        self.layer1 = torch.nn.Sequential(
            torch.nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
            torch.nn.Tanh(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2))

        # 두번째층
        # ImgIn shape=(?, 14, 14, 32)
        #    Conv      ->(?, 14, 14, 64)
        #    Pool      ->(?, 7, 7, 64)
        self.layer2 = torch.nn.Sequential(
            torch.nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            torch.nn.Tanh(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2))

        # 전결합층 7x7x64 inputs -> 10 outputs
        self.fc = torch.nn.Linear(7 * 7 * 64, 10, bias=True)

        # 전결합층 한정으로 가중치 초기화
        torch.nn.init.xavier_uniform_(self.fc.weight)

    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = out.view(out.size(0), -1)   # 전결합층을 위해서 Flatten
        out = self.fc(out)
        return out

In [138]:
# 모델을 정의합니다.

# CNN 모델 정의
model = CNN().to(device)
# 비용 함수와 옵티마이저를 정의합니다.

criterion = torch.nn.CrossEntropyLoss().to(device)    # 비용 함수에 소프트맥스 함수 포함되어져 있음.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
# 총 배치의 수를 출력해보겠습니다.

total_batch = len(data_loader)
print('총 배치의 수 : {}'.format(total_batch))
# 총 배치의 수 : 600
# 총 배치의 수는 600입니다. 그런데 배치 크기를 100으로 했으므로 결국 훈련 데이터는 총 60,000개란 의미입니다. 이제 모델을 훈련시켜보겠습니다. (시간이 꽤 오래 걸립니다.)

for epoch in range(training_epochs):
    avg_cost = 0

    for X, Y in data_loader: # 미니 배치 단위로 꺼내온다. X는 미니 배치, Y는 레이블.
        # image is already size of (28x28), no reshape
        # label is not one-hot encoded
        X = X.to(device)
        Y = Y.to(device)

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

    print('[Epoch: {:>4}] cost = {:>.9}'.format(epoch + 1, avg_cost))

총 배치의 수 : 30
[Epoch:    1] cost = 0.112832822
[Epoch:    2] cost = 0.0142681515
[Epoch:    3] cost = 0.0116213951
[Epoch:    4] cost = 0.0120147942
[Epoch:    5] cost = 0.0196542889
[Epoch:    6] cost = 0.00492227357
[Epoch:    7] cost = 0.00171656837
[Epoch:    8] cost = 0.000686642074
[Epoch:    9] cost = 0.000442401128
[Epoch:   10] cost = 0.000278438238
[Epoch:   11] cost = 0.000239286892
[Epoch:   12] cost = 0.000175217836
[Epoch:   13] cost = 0.000151890839
[Epoch:   14] cost = 0.000131074761
[Epoch:   15] cost = 0.000115670962


In [ ]:
# 결과 예측 하기 
# 참고 사이트 
"""
https://github.com/MLlounge/ML-Project/blob/master/Basic%20Project/CNN%20-%20Distinguish%20language%20according%20to%20characters/CNN%20-%20Distinguish%20language%20according%20to%20characters.py
"""

In [13]:
from PIL import Image 


# img = Image.open("./normal_data/normal_align_test_image/20200518_test_inadvance1_off.jpeg")
# img.size

#  # # 이미지 흑백으로 변경 
#       img = thedata2.convert('L')
#       # # 이미지를 28, 28로 일괄 리사이즈 
#       resize_img = img.resize((28,28))
#       black_resize_img = np.asarray(resize_img)
#       # # 가공한 이미지 추가 
#       data.append(black_resize_img)
#       # # label : broken, insect, normal
#       label.append(i)

#       fp.close()




# read image and image preprocessing 
pre_img = Image.open("./normal_data/normal_align_test_image/20200518_test_inadvance3.jpeg")
pre_img = pre_img.convert("L") # change into black-and-white image
pre_img = pre_img.resize((28,28)) # resize image to 32 * 32 * 1 
pre_data = np.asarray(pre_img) # np type 
#pre_data = 1 * (pre_data > np.mean(pre_data)) # change to binary data 
#pre_data = np.reshape(pre_data, [-1, 28, 28, 1])
type(pre_data), pre_data.size

FileNotFoundError: [Errno 2] No such file or directory: './normal_data/normal_align_test_image/20200518_test_inadvance3.jpeg'

In [ ]:
# prediction 
pre_result = model.predict(pre_data)

print(pre_result)
